### ISSUE TITLE
Package installs as unknown

### ISSUE THREAD

**Issue by abourramouss** [CLOUDLAB-URV/dataplug#11]
Hello,
When following the instructions and installing dataplug (python3.10 -m pip install git+https://github.com/CLOUDLAB-URV/dataplug), I get that it installs with the name UNKNOWN.

`Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/CLOUDLAB-URV/dataplug
  Cloning https://github.com/CLOUDLAB-URV/dataplug to /tmp/pip-req-build-urvazft6
  Running command git clone --filter=blob:none --quiet https://github.com/CLOUDLAB-URV/dataplug /tmp/pip-req-build-urvazft6
  Resolved https://github.com/CLOUDLAB-URV/dataplug to commit 00c2d33adaaf12afb496376a608d75aaebe149ee
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=5111 sha256=da3a237925742fed21d7864dc7e836acd30cd56f2410a0080d2ec614f2a948a6
  Stored in directory: /tmp/pip-ephem-wheel-cache-5x9vu5qo/wheels/f1/33/ac/8063c3fc2c010e8f5a53a4d71798589bf80876a3bd00be5c1c
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0`

Any way I could also install it in developement mode? (pip install -e .)

**Comment by aitorarjona** [comment]
Can you try using a virtual environment?
To install in development mode, you have to first clone the whole repository, cd into it and install in editable mode, as usual: https://setuptools.pypa.io/en/latest/userguide/development_mode.html

**Comment by abourramouss** [comment]
Using a venv fixed the issue, thanks.

**Comment by aitorarjona** [comment]
In fact, I believe it's no longer possible to install system-wide pip packages anymore. You must use venvs. This is the message that I get if I run `python3 -m pip install git+https://github.com/CLOUDLAB-URV/dataplug` (Python 3.11.4, pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11))
```
rror: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
